### ISSUE TITLE
INFO parser returns only first element after splitting by comma for certain fields

### ISSUE THREAD

**Issue by GlyphDataServices** [jdoughertyii/PyVCF#10]
I'm tweaking the info parser. Would like to speak with someone regarding the best approach.  I'm a bit confused about this line: 

`self.infos[ID].num == 1 and entry_type not in ( 'Flag' )`

seems that this condition is used to determine whether to return only the first element after splitting by comma. This results in a loss of multiple RS values (dbSNP ids) among other values in the source VCF. 

Any suggestions?   my approach is to detect the presence of delimiting characters in the source string such as comma or pipe in an attempt to extend the parsing to nested data such as RS=123,234

Maybe i'm missing something here, but some of these csv fields are truncated in the final output.

**Comment by jdoughertyii** [comment]
This branch is no longer actively maintained.  The development repository for PyVCF is at https://github.com/jamescasbon/PyVCF
